// GENERATED by tools/capture.py — verbatim surfaces from a fresh materialization of
// examples/. Do not edit; re-run the script.
export const CAPTURES = {
  "provenance": {
    "capturedAt": "2026-09-07T08:42:04+00:00",
    "claimsLedgerCommit": "c5f6a12",
    "claimsLedgerVersion": "claims-ledger 0.1.0",
    "materializedWith": "examples/materialize.py",
    "repository": "research-repo",
    "pinnedCommit": "@2dbe114d846e4ec0aab4baa523d5314d3ba8a7ad",
    "how": "status; check; append one refuted verdict to R0001 by hand; status; check; propagate --write; status; git add -A; git commit (the installed hook runs)"
  },
  "entryBefore": "---\nid: R0001-threshold-balances-review-errors\nkind: claim\nstated: 2026-09-06T09:00:00-07:00\nauthor: main\ngrade: preregistered\nsupersedes: none\nverbatim_sha: 9dcc6db7e921d0896b7939a2397247c206d78ae26bd4787f379fb380f4d9245f\n---\n\n## Assertion\n\nIn pilot-a, a threshold of 0.72 keeps the false-review rate at 0.14 and the miss rate at\n0.05.\n\n## Scope\n\nmetric: false-review rate and miss rate\ncohort: synthetic pilot-a rows\ncondition: threshold fixed at 0.72 before the demonstration run\n\n## Grounds\n\n- experiment: experiments/threshold.csv @2dbe114d846e4ec0aab4baa523d5314d3ba8a7ad\n- source: latency-paper · demonstration cohort\n\n## Warrant\n\nThe preregistered row directly records both rates at the fixed threshold, while the\nsource independently constrains the operating condition used in the fictional study.\n\n## Backing\n\n- source: latency-paper · demonstration cohort\n  speaker: Rao and Bell\n  quote: \"In the demonstration cohort, the median review latency remained below two minutes at a threshold of 0.72.\"\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n\n## References\n\n- README.md · standing · cites-as-live\n- ROSTER.md · standing · cites-as-live\n",
  "entryAfter": "---\nid: R0001-threshold-balances-review-errors\nkind: claim\nstated: 2026-09-06T09:00:00-07:00\nauthor: main\ngrade: preregistered\nsupersedes: none\nverbatim_sha: 9dcc6db7e921d0896b7939a2397247c206d78ae26bd4787f379fb380f4d9245f\n---\n\n## Assertion\n\nIn pilot-a, a threshold of 0.72 keeps the false-review rate at 0.14 and the miss rate at\n0.05.\n\n## Scope\n\nmetric: false-review rate and miss rate\ncohort: synthetic pilot-a rows\ncondition: threshold fixed at 0.72 before the demonstration run\n\n## Grounds\n\n- experiment: experiments/threshold.csv @2dbe114d846e4ec0aab4baa523d5314d3ba8a7ad\n- source: latency-paper · demonstration cohort\n\n## Warrant\n\nThe preregistered row directly records both rates at the fixed threshold, while the\nsource independently constrains the operating condition used in the fictional study.\n\n## Backing\n\n- source: latency-paper · demonstration cohort\n  speaker: Rao and Bell\n  quote: \"In the demonstration cohort, the median review latency remained below two minutes at a threshold of 0.72.\"\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n- 2026-09-07T09:00:00-07:00 · refuted · grade: preregistered · author: main\n  evidence: experiment: experiments/threshold.csv @2dbe114d846e4ec0aab4baa523d5314d3ba8a7ad\n  note: the pilot-b rerun put the miss rate at 0.09\n\n\n## References\n\n- README.md · standing · cites-as-live\n- ROSTER.md · standing · cites-as-live\n",
  "verdictRow": "- 2026-09-07T09:00:00-07:00 · refuted · grade: preregistered · author: main\n  evidence: experiment: experiments/threshold.csv @2dbe114d846e4ec0aab4baa523d5314d3ba8a7ad\n  note: the pilot-b rerun put the miss rate at 0.09\n",
  "dependentAfter": "---\nid: R0003-threshold-generalizes\nkind: hypothesis\nstated: 2026-09-06T09:10:00-07:00\nauthor: main\ngrade: argued\ncredence: 0.55\nresolves_when: the preregistered pilot-b threshold sweep resolves\nsupersedes: none\nverbatim_sha: b4dfa3760bdf764c092ef6486a0c63772313104a61167e909352ce45f2d80e0b\n---\n\n## Assertion\n\nThe 0.72 threshold will preserve both error-rate margins when transferred from pilot-a\nto pilot-b.\n\n## Scope\n\nmetric: false-review rate at most 0.16 and miss rate at most 0.07\ncohort: synthetic pilot-b rows\ncondition: scoring model and review policy held fixed\n\n## Grounds\n\n- entry: R0001-threshold-balances-review-errors · cites-as-live\n- entry: R0002-review-latency-stays-low · cites-as-live\n\n## Warrant\n\nThe first pilot leaves margin on both rates and the latency prediction implies adequate\nreview capacity. Falsified if either preregistered pilot-b error rate exceeds its margin.\n\n## Backing\n\nnone\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n- 2026-09-07T01:42:03-07:00 · contested · grade: preregistered · author: propagation\n  evidence: entry: R0001-threshold-balances-review-errors · fallen\n  note: R0001-threshold-balances-review-errors refuted (verdict 1, 2026-09-07T09:00:00-07:00)\n\n## References\n\n- ROSTER.md · standing · cites-as-live\n",
  "statusBefore": {
    "argv": [
      "claims-ledger",
      "status"
    ],
    "exit": 0,
    "text": "R0001-threshold-balances-review-errors           claim      preregistered open\nR0002-review-latency-stays-low                   prediction argued        open\nR0003-threshold-generalizes                      hypothesis argued        open\nR0004-no-calibration-study-found                 claim      asserted      open\nR0005-threshold-rounds-to-seven-tenths           claim      measured      superseded\nR0006-threshold-displays-as-seventy-two-percent  claim      measured      open\nR0007-threshold-is-cohort-invariant              claim      measured      contested\nR0008-one-cohort-cannot-establish-invariance     claim      measured      open\nR0009-threshold-direction-replicates             claim      measured      corroborated\nR0010-consultation-wording-retracted             claim      asserted      retracted\nR0011-single-cohort-generalization-refuted       claim      measured      refuted\nR0012-latency-and-error-rates-non-comparable     claim      measured      non-comparable\n\n12 entries in ledger/entries"
  },
  "checkBefore": {
    "argv": [
      "claims-ledger",
      "check"
    ],
    "exit": 0,
    "text": "validate: 0 failure(s), 0 flag(s)\nresolve: 0 failure(s), 0 flag(s)\nreferences: 0 failure(s), 0 flag(s)\npropagate: 0 failure(s), 0 flag(s)\nfreshness: 0 failure(s), 0 flag(s)"
  },
  "statusAfterVerdict": {
    "argv": [
      "claims-ledger",
      "status"
    ],
    "exit": 0,
    "text": "R0001-threshold-balances-review-errors           claim      preregistered refuted\nR0002-review-latency-stays-low                   prediction argued        open\nR0003-threshold-generalizes                      hypothesis argued        open\nR0004-no-calibration-study-found                 claim      asserted      open\nR0005-threshold-rounds-to-seven-tenths           claim      measured      superseded\nR0006-threshold-displays-as-seventy-two-percent  claim      measured      open\nR0007-threshold-is-cohort-invariant              claim      measured      contested\nR0008-one-cohort-cannot-establish-invariance     claim      measured      open\nR0009-threshold-direction-replicates             claim      measured      corroborated\nR0010-consultation-wording-retracted             claim      asserted      retracted\nR0011-single-cohort-generalization-refuted       claim      measured      refuted\nR0012-latency-and-error-rates-non-comparable     claim      measured      non-comparable\n\n12 entries in ledger/entries"
  },
  "checkAfterVerdict": {
    "argv": [
      "claims-ledger",
      "check"
    ],
    "exit": 1,
    "text": "validate: 0 failure(s), 0 flag(s)\nresolve: 0 failure(s), 0 flag(s)\nFAIL R0002 Grounds: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL R0003 Grounds: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL README.md: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL ROSTER.md: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nreferences: 4 failure(s), 0 flag(s)\nFAIL R0002 Verdicts: cites R0001-threshold-balances-review-errors cites-as-live and R0001-threshold-balances-review-errors has fallen to refuted, but carries no contested verdict by propagation naming it\nFAIL R0003 Verdicts: cites R0001-threshold-balances-review-errors cites-as-live and R0001-threshold-balances-review-errors has fallen to refuted, but carries no contested verdict by propagation naming it\npropagate: 2 failure(s), 0 flag(s)\nfreshness: 0 failure(s), 0 flag(s)"
  },
  "propagate": {
    "argv": [
      "claims-ledger",
      "propagate",
      "--write"
    ],
    "exit": 1,
    "text": "FAIL R0002 Verdicts: cites R0001-threshold-balances-review-errors cites-as-live and R0001-threshold-balances-review-errors has fallen to refuted, but carries no contested verdict by propagation naming it\nFAIL R0003 Verdicts: cites R0001-threshold-balances-review-errors cites-as-live and R0001-threshold-balances-review-errors has fallen to refuted, but carries no contested verdict by propagation naming it\nFLAG R0002 Verdicts: appended 1 contested verdict(s) by propagation\nFLAG R0003 Verdicts: appended 1 contested verdict(s) by propagation\npropagate (12 entries): 2 failure(s), 2 flag(s)"
  },
  "statusAfterPropagate": {
    "argv": [
      "claims-ledger",
      "status"
    ],
    "exit": 0,
    "text": "R0001-threshold-balances-review-errors           claim      preregistered refuted\nR0002-review-latency-stays-low                   prediction argued        contested\nR0003-threshold-generalizes                      hypothesis argued        contested\nR0004-no-calibration-study-found                 claim      asserted      open\nR0005-threshold-rounds-to-seven-tenths           claim      measured      superseded\nR0006-threshold-displays-as-seventy-two-percent  claim      measured      open\nR0007-threshold-is-cohort-invariant              claim      measured      contested\nR0008-one-cohort-cannot-establish-invariance     claim      measured      open\nR0009-threshold-direction-replicates             claim      measured      corroborated\nR0010-consultation-wording-retracted             claim      asserted      retracted\nR0011-single-cohort-generalization-refuted       claim      measured      refuted\nR0012-latency-and-error-rates-non-comparable     claim      measured      non-comparable\n\n12 entries in ledger/entries"
  },
  "commit": {
    "argv": [
      "git",
      "commit",
      "-m",
      "refute R0001"
    ],
    "exit": 1,
    "text": "validate (12 entries): 0 failure(s), 0 flag(s)\nresolve (12 entries): 0 failure(s), 0 flag(s)\nFAIL R0002 Grounds: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL R0003 Grounds: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL R0003 Grounds: cites-as-live against R0002-review-latency-stays-low, whose status is contested; cites-as-live needs corroborated or open\nFAIL README.md: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL ROSTER.md: cites-as-live against R0003-threshold-generalizes, whose status is contested; cites-as-live needs corroborated or open\nFAIL ROSTER.md: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL ROSTER.md: cites-as-live against R0002-review-latency-stays-low, whose status is contested; cites-as-live needs corroborated or open\nFAIL ROSTER.md: row for R0003-threshold-generalizes says `open`; the entry's status is `contested`\nreferences (12 entries, 3 documents): 8 failure(s), 0 flag(s)"
  },
  "headAfterCommit": "c1010f6 Add checked claims ledger"
} as const;
