// GENERATED by tools/capture.py — verbatim surfaces from fresh materializations of
// examples/. Do not edit; re-run the script.
export const CAPTURES = {
  "provenance": {
    "capturedAt": "2026-09-07T10:23:55+00:00",
    "claimsLedgerCommit": "b610d2d",
    "claimsLedgerVersion": "claims-ledger 0.1.0",
    "materializedWith": "examples/materialize.py",
    "repository": "research-repo",
    "how": "per scenario, in a fresh materialization: status; check; write the new entry and `sha --write` it; append the verdict to the old entry by hand; status; check; propagate --write and status (refuted only); git add -A; git commit (the installed hook runs)"
  },
  "refuted": {
    "entryId": "R0001-threshold-balances-review-errors",
    "entryPath": "ledger/entries/R0001-threshold-balances-review-errors.md",
    "entryBefore": "---\nid: R0001-threshold-balances-review-errors\nkind: claim\nstated: 2026-09-06T09:00:00-07:00\nauthor: main\ngrade: preregistered\nsupersedes: none\nverbatim_sha: 9dcc6db7e921d0896b7939a2397247c206d78ae26bd4787f379fb380f4d9245f\n---\n\n## Assertion\n\nIn pilot-a, a threshold of 0.72 keeps the false-review rate at 0.14 and the miss rate at\n0.05.\n\n## Scope\n\nmetric: false-review rate and miss rate\ncohort: synthetic pilot-a rows\ncondition: threshold fixed at 0.72 before the demonstration run\n\n## Grounds\n\n- experiment: experiments/threshold.csv @5ff3b1ec969cc4342ee5feec3c65dc48f1b27401\n- source: latency-paper · demonstration cohort\n\n## Warrant\n\nThe preregistered row directly records both rates at the fixed threshold, while the\nsource independently constrains the operating condition used in the fictional study.\n\n## Backing\n\n- source: latency-paper · demonstration cohort\n  speaker: Rao and Bell\n  quote: \"In the demonstration cohort, the median review latency remained below two minutes at a threshold of 0.72.\"\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n\n## References\n\n- README.md · standing · cites-as-live\n- ROSTER.md · standing · cites-as-live\n",
    "entryAfter": "---\nid: R0001-threshold-balances-review-errors\nkind: claim\nstated: 2026-09-06T09:00:00-07:00\nauthor: main\ngrade: preregistered\nsupersedes: none\nverbatim_sha: 9dcc6db7e921d0896b7939a2397247c206d78ae26bd4787f379fb380f4d9245f\n---\n\n## Assertion\n\nIn pilot-a, a threshold of 0.72 keeps the false-review rate at 0.14 and the miss rate at\n0.05.\n\n## Scope\n\nmetric: false-review rate and miss rate\ncohort: synthetic pilot-a rows\ncondition: threshold fixed at 0.72 before the demonstration run\n\n## Grounds\n\n- experiment: experiments/threshold.csv @5ff3b1ec969cc4342ee5feec3c65dc48f1b27401\n- source: latency-paper · demonstration cohort\n\n## Warrant\n\nThe preregistered row directly records both rates at the fixed threshold, while the\nsource independently constrains the operating condition used in the fictional study.\n\n## Backing\n\n- source: latency-paper · demonstration cohort\n  speaker: Rao and Bell\n  quote: \"In the demonstration cohort, the median review latency remained below two minutes at a threshold of 0.72.\"\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n- 2026-09-07T09:05:00-07:00 · refuted · grade: measured · author: main\n  evidence: entry: R0013-pilot-b-miss-rate-exceeds-margin · cites-as-live\n  note: pilot-b does not hold the miss-rate margin\n\n\n## References\n\n- README.md · standing · cites-as-live\n- ROSTER.md · standing · cites-as-live\n",
    "verdictRow": "- 2026-09-07T09:05:00-07:00 · refuted · grade: measured · author: main\n  evidence: entry: R0013-pilot-b-miss-rate-exceeds-margin · cites-as-live\n  note: pilot-b does not hold the miss-rate margin\n",
    "newId": "R0013-pilot-b-miss-rate-exceeds-margin",
    "newPath": "ledger/entries/R0013-pilot-b-miss-rate-exceeds-margin.md",
    "newText": "---\nid: R0013-pilot-b-miss-rate-exceeds-margin\nkind: claim\nstated: 2026-09-07T09:00:00-07:00\nauthor: main\ngrade: measured\nsupersedes: none\nverbatim_sha: 8c7cf45f61cf92b5fed23f89ab0e64ec1551180412cc08d995b62f8b7c0e6d97\n---\n\n## Assertion\n\nIn pilot-b, the 0.72 threshold puts the miss rate at 0.09, above the 0.05 that pilot-a\nrecorded.\n\n## Scope\n\nmetric: miss rate\ncohort: synthetic pilot-b rows\ncondition: threshold fixed at 0.72, scoring model and review policy held fixed\n\n## Grounds\n\n- experiment: experiments/threshold.csv @5ff3b1ec969cc4342ee5feec3c65dc48f1b27401\n\n## Warrant\n\nThe rerun row records the pilot-b miss rate directly; it exceeds the pilot-a figure the\nearlier claim rests on.\n\n## Backing\n\nnone\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n\n## References\n\n",
    "sha": {
      "argv": [
        "claims-ledger",
        "sha",
        "--write",
        "ledger/entries/R0013-pilot-b-miss-rate-exceeds-margin.md"
      ],
      "exit": 0,
      "text": "ledger/entries/R0013-pilot-b-miss-rate-exceeds-margin.md: 0… → 8c7cf45f61cf…"
    },
    "dependentId": "R0003-threshold-generalizes",
    "dependentPath": "ledger/entries/R0003-threshold-generalizes.md",
    "dependentAfter": "---\nid: R0003-threshold-generalizes\nkind: hypothesis\nstated: 2026-09-06T09:10:00-07:00\nauthor: main\ngrade: argued\ncredence: 0.55\nresolves_when: the preregistered pilot-b threshold sweep resolves\nsupersedes: none\nverbatim_sha: b4dfa3760bdf764c092ef6486a0c63772313104a61167e909352ce45f2d80e0b\n---\n\n## Assertion\n\nThe 0.72 threshold will preserve both error-rate margins when transferred from pilot-a\nto pilot-b.\n\n## Scope\n\nmetric: false-review rate at most 0.16 and miss rate at most 0.07\ncohort: synthetic pilot-b rows\ncondition: scoring model and review policy held fixed\n\n## Grounds\n\n- entry: R0001-threshold-balances-review-errors · cites-as-live\n- entry: R0002-review-latency-stays-low · cites-as-live\n\n## Warrant\n\nThe first pilot leaves margin on both rates and the latency prediction implies adequate\nreview capacity. Falsified if either preregistered pilot-b error rate exceeds its margin.\n\n## Backing\n\nnone\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n- 2026-09-07T03:23:59-07:00 · contested · grade: measured · author: propagation\n  evidence: entry: R0001-threshold-balances-review-errors · fallen\n  note: R0001-threshold-balances-review-errors refuted (verdict 1, 2026-09-07T09:05:00-07:00)\n\n## References\n\n- ROSTER.md · standing · cites-as-live\n",
    "statusBefore": {
      "argv": [
        "claims-ledger",
        "status"
      ],
      "exit": 0,
      "text": "R0001-threshold-balances-review-errors           claim      preregistered open\nR0002-review-latency-stays-low                   prediction argued        open\nR0003-threshold-generalizes                      hypothesis argued        open\nR0004-no-calibration-study-found                 claim      asserted      open\nR0005-threshold-rounds-to-seven-tenths           claim      measured      superseded\nR0006-threshold-displays-as-seventy-two-percent  claim      measured      open\nR0007-threshold-is-cohort-invariant              claim      measured      contested\nR0008-one-cohort-cannot-establish-invariance     claim      measured      open\nR0009-threshold-direction-replicates             claim      measured      corroborated\nR0010-consultation-wording-retracted             claim      asserted      retracted\nR0011-single-cohort-generalization-refuted       claim      measured      refuted\nR0012-latency-and-error-rates-non-comparable     claim      measured      non-comparable\n\n12 entries in ledger/entries"
    },
    "checkBefore": {
      "argv": [
        "claims-ledger",
        "check"
      ],
      "exit": 0,
      "text": "validate: 0 failure(s), 0 flag(s)\nresolve: 0 failure(s), 0 flag(s)\nreferences: 0 failure(s), 0 flag(s)\npropagate: 0 failure(s), 0 flag(s)\nfreshness: 0 failure(s), 0 flag(s)"
    },
    "statusAfterVerdict": {
      "argv": [
        "claims-ledger",
        "status"
      ],
      "exit": 0,
      "text": "R0001-threshold-balances-review-errors           claim      preregistered refuted\nR0002-review-latency-stays-low                   prediction argued        open\nR0003-threshold-generalizes                      hypothesis argued        open\nR0004-no-calibration-study-found                 claim      asserted      open\nR0005-threshold-rounds-to-seven-tenths           claim      measured      superseded\nR0006-threshold-displays-as-seventy-two-percent  claim      measured      open\nR0007-threshold-is-cohort-invariant              claim      measured      contested\nR0008-one-cohort-cannot-establish-invariance     claim      measured      open\nR0009-threshold-direction-replicates             claim      measured      corroborated\nR0010-consultation-wording-retracted             claim      asserted      retracted\nR0011-single-cohort-generalization-refuted       claim      measured      refuted\nR0012-latency-and-error-rates-non-comparable     claim      measured      non-comparable\nR0013-pilot-b-miss-rate-exceeds-margin           claim      measured      open\n\n13 entries in ledger/entries"
    },
    "checkAfterVerdict": {
      "argv": [
        "claims-ledger",
        "check"
      ],
      "exit": 1,
      "text": "FLAG R0001 verdict 1: refuted on measured evidence against a preregistered entry; evidence types are not ranked, so this is for review\nvalidate: 0 failure(s), 1 flag(s)\nresolve: 0 failure(s), 0 flag(s)\nFAIL R0002 Grounds: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL R0003 Grounds: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL README.md: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL ROSTER.md: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nreferences: 4 failure(s), 0 flag(s)\nFAIL R0002 Verdicts: cites R0001-threshold-balances-review-errors cites-as-live and R0001-threshold-balances-review-errors has fallen to refuted, but carries no contested verdict by propagation naming it\nFAIL R0003 Verdicts: cites R0001-threshold-balances-review-errors cites-as-live and R0001-threshold-balances-review-errors has fallen to refuted, but carries no contested verdict by propagation naming it\npropagate: 2 failure(s), 0 flag(s)\nfreshness: 0 failure(s), 0 flag(s)"
    },
    "propagate": {
      "argv": [
        "claims-ledger",
        "propagate",
        "--write"
      ],
      "exit": 1,
      "text": "FAIL R0002 Verdicts: cites R0001-threshold-balances-review-errors cites-as-live and R0001-threshold-balances-review-errors has fallen to refuted, but carries no contested verdict by propagation naming it\nFAIL R0003 Verdicts: cites R0001-threshold-balances-review-errors cites-as-live and R0001-threshold-balances-review-errors has fallen to refuted, but carries no contested verdict by propagation naming it\nFLAG R0002 Verdicts: appended 1 contested verdict(s) by propagation\nFLAG R0003 Verdicts: appended 1 contested verdict(s) by propagation\npropagate (13 entries): 2 failure(s), 2 flag(s)"
    },
    "statusAfterPropagate": {
      "argv": [
        "claims-ledger",
        "status"
      ],
      "exit": 0,
      "text": "R0001-threshold-balances-review-errors           claim      preregistered refuted\nR0002-review-latency-stays-low                   prediction argued        contested\nR0003-threshold-generalizes                      hypothesis argued        contested\nR0004-no-calibration-study-found                 claim      asserted      open\nR0005-threshold-rounds-to-seven-tenths           claim      measured      superseded\nR0006-threshold-displays-as-seventy-two-percent  claim      measured      open\nR0007-threshold-is-cohort-invariant              claim      measured      contested\nR0008-one-cohort-cannot-establish-invariance     claim      measured      open\nR0009-threshold-direction-replicates             claim      measured      corroborated\nR0010-consultation-wording-retracted             claim      asserted      retracted\nR0011-single-cohort-generalization-refuted       claim      measured      refuted\nR0012-latency-and-error-rates-non-comparable     claim      measured      non-comparable\nR0013-pilot-b-miss-rate-exceeds-margin           claim      measured      open\n\n13 entries in ledger/entries"
    },
    "commit": {
      "argv": [
        "git",
        "commit",
        "-m",
        "refute R0001"
      ],
      "exit": 1,
      "text": "FLAG R0001 verdict 1: refuted on measured evidence against a preregistered entry; evidence types are not ranked, so this is for review\nvalidate (13 entries): 0 failure(s), 1 flag(s)\nresolve (13 entries): 0 failure(s), 0 flag(s)\nFAIL R0002 Grounds: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL R0003 Grounds: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL R0003 Grounds: cites-as-live against R0002-review-latency-stays-low, whose status is contested; cites-as-live needs corroborated or open\nFAIL README.md: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL ROSTER.md: cites-as-live against R0003-threshold-generalizes, whose status is contested; cites-as-live needs corroborated or open\nFAIL ROSTER.md: cites-as-live against R0001-threshold-balances-review-errors, whose status is refuted; cites-as-live needs corroborated or open\nFAIL ROSTER.md: cites-as-live against R0002-review-latency-stays-low, whose status is contested; cites-as-live needs corroborated or open\nFAIL ROSTER.md: row for R0003-threshold-generalizes says `open`; the entry's status is `contested`\nreferences (13 entries, 3 documents): 8 failure(s), 0 flag(s)"
    },
    "headAfterCommit": "929943c Add checked claims ledger",
    "pinnedCommit": "@5ff3b1ec969cc4342ee5feec3c65dc48f1b27401"
  },
  "superseded": {
    "entryId": "R0006-threshold-displays-as-seventy-two-percent",
    "entryPath": "ledger/entries/R0006-threshold-displays-as-seventy-two-percent.md",
    "entryBefore": "---\nid: R0006-threshold-displays-as-seventy-two-percent\nkind: claim\nstated: 2026-09-06T09:25:00-07:00\nauthor: main\ngrade: measured\nsupersedes: R0005-threshold-rounds-to-seven-tenths\nverbatim_sha: e40d061ae208b1c3b1f6faffe5ce818de99f98864c05353604b90a28e72ecac7\n---\n\n## Assertion\n\nThe selected demonstration threshold displays exactly as 72 percent.\n\n## Scope\n\nmetric: threshold rounded to one decimal place\ncohort: synthetic pilot-a selected row\ncondition: ordinary half-up decimal presentation\n\n## Grounds\n\n- experiment: experiments/threshold.csv @bfc5fbcf9f321f7a1c5b95de7e784af24dac1dab\n\n## Warrant\n\nThe same selected row records 0.72; retaining two digits communicates the configured\nboundary without the information loss in the predecessor.\n\n## Backing\n\nnone\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n\n## References\n\n",
    "entryAfter": "---\nid: R0006-threshold-displays-as-seventy-two-percent\nkind: claim\nstated: 2026-09-06T09:25:00-07:00\nauthor: main\ngrade: measured\nsupersedes: R0005-threshold-rounds-to-seven-tenths\nverbatim_sha: e40d061ae208b1c3b1f6faffe5ce818de99f98864c05353604b90a28e72ecac7\n---\n\n## Assertion\n\nThe selected demonstration threshold displays exactly as 72 percent.\n\n## Scope\n\nmetric: threshold rounded to one decimal place\ncohort: synthetic pilot-a selected row\ncondition: ordinary half-up decimal presentation\n\n## Grounds\n\n- experiment: experiments/threshold.csv @bfc5fbcf9f321f7a1c5b95de7e784af24dac1dab\n\n## Warrant\n\nThe same selected row records 0.72; retaining two digits communicates the configured\nboundary without the information loss in the predecessor.\n\n## Backing\n\nnone\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n- 2026-09-07T09:05:00-07:00 · superseded · grade: measured · author: main\n  evidence: entry: R0013-threshold-displays-as-seventy-two-percent-everywhere · supersedes\n  note: replaced by the claim about every surface\n\n\n## References\n\n",
    "verdictRow": "- 2026-09-07T09:05:00-07:00 · superseded · grade: measured · author: main\n  evidence: entry: R0013-threshold-displays-as-seventy-two-percent-everywhere · supersedes\n  note: replaced by the claim about every surface\n",
    "newId": "R0013-threshold-displays-as-seventy-two-percent-everywhere",
    "newPath": "ledger/entries/R0013-threshold-displays-as-seventy-two-percent-everywhere.md",
    "newText": "---\nid: R0013-threshold-displays-as-seventy-two-percent-everywhere\nkind: claim\nstated: 2026-09-07T09:00:00-07:00\nauthor: main\ngrade: measured\nsupersedes: R0006-threshold-displays-as-seventy-two-percent\nverbatim_sha: e40d061ae208b1c3b1f6faffe5ce818de99f98864c05353604b90a28e72ecac7\n---\n\n## Assertion\n\nThe selected demonstration threshold displays as 72 percent on every surface that shows\nit, not only the console banner.\n\n## Scope\n\nmetric: threshold rounded to one decimal place\ncohort: synthetic pilot-a selected row\ncondition: ordinary half-up decimal presentation\n\n## Grounds\n\n- experiment: experiments/threshold.csv @bfc5fbcf9f321f7a1c5b95de7e784af24dac1dab\n\n## Warrant\n\nThe same selected row records 0.72; the predecessor named one surface, and the display\nrule is the same on all of them.\n\n## Backing\n\nnone\n\n<!-- APPEND BELOW THIS LINE ONLY -->\n\n## Verdicts\n\n\n## References\n\n",
    "sha": {
      "argv": [
        "claims-ledger",
        "sha",
        "--write",
        "ledger/entries/R0013-threshold-displays-as-seventy-two-percent-everywhere.md"
      ],
      "exit": 0,
      "text": "ledger/entries/R0013-threshold-displays-as-seventy-two-percent-everywhere.md: 0… → e40d061ae208…"
    },
    "dependentId": null,
    "dependentPath": null,
    "dependentAfter": null,
    "statusBefore": {
      "argv": [
        "claims-ledger",
        "status"
      ],
      "exit": 0,
      "text": "R0001-threshold-balances-review-errors           claim      preregistered open\nR0002-review-latency-stays-low                   prediction argued        open\nR0003-threshold-generalizes                      hypothesis argued        open\nR0004-no-calibration-study-found                 claim      asserted      open\nR0005-threshold-rounds-to-seven-tenths           claim      measured      superseded\nR0006-threshold-displays-as-seventy-two-percent  claim      measured      open\nR0007-threshold-is-cohort-invariant              claim      measured      contested\nR0008-one-cohort-cannot-establish-invariance     claim      measured      open\nR0009-threshold-direction-replicates             claim      measured      corroborated\nR0010-consultation-wording-retracted             claim      asserted      retracted\nR0011-single-cohort-generalization-refuted       claim      measured      refuted\nR0012-latency-and-error-rates-non-comparable     claim      measured      non-comparable\n\n12 entries in ledger/entries"
    },
    "checkBefore": {
      "argv": [
        "claims-ledger",
        "check"
      ],
      "exit": 0,
      "text": "validate: 0 failure(s), 0 flag(s)\nresolve: 0 failure(s), 0 flag(s)\nreferences: 0 failure(s), 0 flag(s)\npropagate: 0 failure(s), 0 flag(s)\nfreshness: 0 failure(s), 0 flag(s)"
    },
    "statusAfterVerdict": {
      "argv": [
        "claims-ledger",
        "status"
      ],
      "exit": 0,
      "text": "R0001-threshold-balances-review-errors                      claim      preregistered open\nR0002-review-latency-stays-low                              prediction argued        open\nR0003-threshold-generalizes                                 hypothesis argued        open\nR0004-no-calibration-study-found                            claim      asserted      open\nR0005-threshold-rounds-to-seven-tenths                      claim      measured      superseded\nR0006-threshold-displays-as-seventy-two-percent             claim      measured      superseded\nR0007-threshold-is-cohort-invariant                         claim      measured      contested\nR0008-one-cohort-cannot-establish-invariance                claim      measured      open\nR0009-threshold-direction-replicates                        claim      measured      corroborated\nR0010-consultation-wording-retracted                        claim      asserted      retracted\nR0011-single-cohort-generalization-refuted                  claim      measured      refuted\nR0012-latency-and-error-rates-non-comparable                claim      measured      non-comparable\nR0013-threshold-displays-as-seventy-two-percent-everywhere  claim      measured      open\n\n13 entries in ledger/entries"
    },
    "checkAfterVerdict": {
      "argv": [
        "claims-ledger",
        "check"
      ],
      "exit": 0,
      "text": "validate: 0 failure(s), 0 flag(s)\nresolve: 0 failure(s), 0 flag(s)\nreferences: 0 failure(s), 0 flag(s)\npropagate: 0 failure(s), 0 flag(s)\nfreshness: 0 failure(s), 0 flag(s)"
    },
    "propagate": null,
    "statusAfterPropagate": null,
    "commit": {
      "argv": [
        "git",
        "commit",
        "-m",
        "supersede R0006"
      ],
      "exit": 0,
      "text": "validate (13 entries): 0 failure(s), 0 flag(s)\nresolve (13 entries): 0 failure(s), 0 flag(s)\nreferences (13 entries, 3 documents): 0 failure(s), 0 flag(s)\npropagate (13 entries): 0 failure(s), 0 flag(s)\nfreshness (13 entries): 0 failure(s), 0 flag(s)"
    },
    "headAfterCommit": "a70cb40 supersede R0006",
    "pinnedCommit": "@bfc5fbcf9f321f7a1c5b95de7e784af24dac1dab"
  }
} as const;
