#!/usr/bin/env python3
"""Reproduce the film's scenario in a fresh materialization of the example
portfolio and write every surface the film shows, verbatim, to src/captures.ts.

    python3 tools/capture.py

The film draws nothing it invents: the entry, the appended verdict, every
command's output and the hook's refusal are the bytes this script captured,
and the module records when, from which claims-ledger commit, and how.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import UTC, datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
PROJECT = HERE.parent.parent  # the claims-ledger checkout
ENTRY = "ledger/entries/R0001-threshold-balances-review-errors.md"
DEPENDENT = "ledger/entries/R0003-threshold-generalizes.md"
VERDICT_TS = "2026-09-07T09:00:00-07:00"
NOTE = "the pilot-b rerun put the miss rate at 0.09"


def sh(args: list[str], cwd: Path) -> tuple[int, str]:
    p = subprocess.run(args, cwd=cwd, capture_output=True, text=True, check=False)
    return p.returncode, (p.stdout + p.stderr).rstrip("\n")


def main() -> int:
    work = Path(tempfile.mkdtemp(prefix="claims-ledger-film-"))
    dest = work / "portfolio"
    rc, out = sh(
        [
            "uv",
            "run",
            "--project",
            str(PROJECT),
            "python",
            str(PROJECT / "examples" / "materialize.py"),
            str(dest),
        ],
        PROJECT,
    )
    if rc != 0:
        print(out, file=sys.stderr)
        return rc
    repo = dest / "research-repo"
    cl = ["uv", "run", "--project", str(PROJECT), "claims-ledger"]

    def run(*args: str) -> dict[str, object]:
        code, text = sh([*cl, *args], repo)
        return {"argv": ["claims-ledger", *args], "exit": code, "text": text}

    entry_path = repo / ENTRY
    entry_before = entry_path.read_text(encoding="utf-8")
    commit = next(tok for tok in entry_before.split() if tok.startswith("@") and len(tok) == 41)

    status_before = run("status")
    check_before = run("check")

    row = (
        f"- {VERDICT_TS} · refuted · grade: preregistered · author: main\n"
        f"  evidence: experiment: experiments/threshold.csv {commit}\n"
        f"  note: {NOTE}\n"
    )
    assert entry_before.count("## Verdicts\n\n") == 1
    entry_after = entry_before.replace("## Verdicts\n\n", "## Verdicts\n\n" + row + "\n", 1)
    entry_path.write_text(entry_after, encoding="utf-8")

    status_after_verdict = run("status")
    check_after_verdict = run("check")
    propagate = run("propagate", "--write")
    dependent_after = (repo / DEPENDENT).read_text(encoding="utf-8")
    status_after_propagate = run("status")

    sh(["git", "add", "-A"], repo)
    hook_code, hook_text = sh(["git", "commit", "-q", "-m", "refute R0001"], repo)
    _, head_after = sh(["git", "log", "--oneline", "-1"], repo)

    _, cl_commit = sh(["git", "rev-parse", "--short", "HEAD"], PROJECT)
    _, version = sh([*cl, "--version"], PROJECT)

    captures = {
        "provenance": {
            "capturedAt": datetime.now(UTC).isoformat(timespec="seconds"),
            "claimsLedgerCommit": cl_commit,
            "claimsLedgerVersion": version,
            "materializedWith": "examples/materialize.py",
            "repository": "research-repo",
            "pinnedCommit": commit,
            "how": (
                "status; check; append one refuted verdict to R0001 by hand; status; check; "
                "propagate --write; status; git add -A; git commit (the installed hook runs)"
            ),
        },
        "entryBefore": entry_before,
        "entryAfter": entry_after,
        "verdictRow": row,
        "dependentAfter": dependent_after,
        "statusBefore": status_before,
        "checkBefore": check_before,
        "statusAfterVerdict": status_after_verdict,
        "checkAfterVerdict": check_after_verdict,
        "propagate": propagate,
        "statusAfterPropagate": status_after_propagate,
        "commit": {
            "argv": ["git", "commit", "-m", "refute R0001"],
            "exit": hook_code,
            "text": hook_text,
        },
        "headAfterCommit": head_after,
    }
    body = json.dumps(captures, indent=2, ensure_ascii=False)
    (HERE / "src" / "captures.ts").write_text(
        "// GENERATED by tools/capture.py — verbatim surfaces from a fresh materialization of\n"
        "// examples/. Do not edit; re-run the script.\n"
        f"export const CAPTURES = {body} as const;\n",
        encoding="utf-8",
    )
    shutil.rmtree(work, ignore_errors=True)
    print(f"wrote src/captures.ts · hook exit {hook_code} · HEAD after: {head_after}")
    return 0


if __name__ == "__main__":
    os.environ.setdefault("GIT_TERMINAL_PROMPT", "0")
    sys.exit(main())
